name: Build Windows EXE
on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Extract Version from Git Tag
        id: get-version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build JAR
        run: mvn clean package

      - name: Create Windows EXE
        shell: pwsh
        run: |
          echo "Building MSI for AutoClicker version: ${{ env.VERSION }}"
          jpackage --verbose --name AutoClicker `
              --input ./target `
              --main-jar AutoClicker-${{ env.VERSION }}.jar `
              --main-class AutoClicker `
              --name AutoClicker `
              --app-version "${{ env.VERSION }}" `
              --vendor "Ellefsen" `
              --description "Simple Java Swing application AutoClicker that supports clicking on multiple locations" `
              --type msi `
              --win-shortcut `
              --win-menu `
              --win-per-user-install `
              --icon ./mouse.ico `
              --dest ./out/artifacts/AutoClicker

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker-Windows
          path: ./out/artifacts/AutoClicker/AutoClicker-${{ env.VERSION }}.msi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: AutoClicker v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload MSI to GitHub Release
        id: upload-msi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/artifacts/AutoClicker/AutoClicker-${{ env.VERSION }}.msi
          asset_name: AutoClicker-${{ env.VERSION }}.msi
          asset_content_type: application/octet-stream