name: Build Windows EXE
on: push

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build JAR
        run: mvn clean package

      - name: Generate Minimal Java Runtime with jlink
        run: |
          jlink --module-path "%JAVA_HOME%/jmods" `
                --add-modules java.base,java.desktop `
                --output ./runtime `
                --strip-debug `
                --compress 2 `
                --no-header-files `
                --no-man-pages

      - name: Create Windows EXE
        #shell: pwsh  # Ensure the script runs in PowerShell
        run: |
          jpackage --verbose --name AutoClicker `
              --input ./target `
              --main-jar AutoClicker-1.0.jar `
              --main-class AutoClicker `
              --name AutoClicker `
              --app-version 1.0.0 `
              --vendor "Ellefsen" `
              --description "Simple Java Swing application AutoClicker that supports clicking on multiple locations" `
              --type msi `
              --win-shortcut `
              --win-menu `
              --icon ./mouse.ico `
              --runtime-image ./runtime `
              --dest ./out/artifacts/AutoClicker

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker-Windows
          path: ./out/artifacts/AutoClicker/AutoClicker-1.0.0.msi
