name: Build Windows EXE
on: push

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build JAR
        run: mvn clean package

      - name: Create Windows EXE
        shell: pwsh  # Ensure the script runs in PowerShell
        run: |
          jpackage --name AutoClicker `
              --input target `
              --main-jar AutoClicker-1.0.jar `
              --main-class AutoClicker `
              --type exe `
              --win-shortcut `
              --win-menu `
              --icon icon.ico

      - name: Upload EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker-Installer
          path: AutoClicker.exe
